/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tiendasql.UI;

import com.mycompany.tiendasql.ayudaUI.Imagen;
import java.awt.Color;

/**
 *
 * @author lroda
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    //Creamos algunas variables para el mouse
    int mouseX;
    int mouseY;
    
    public Login() {
        initComponents();
        Imagen img = new Imagen();
        this.setIconImage(img.editarIconoApp());
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.jLabelImagen.setIcon(img.editarFondo(jLabelImagen, "/Panel-Gris.jpg"));
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jLabelB = new javax.swing.JLabel();
        jLabelI = new javax.swing.JLabel();
        jLabelE = new javax.swing.JLabel();
        jLabelN = new javax.swing.JLabel();
        jLabelV = new javax.swing.JLabel();
        jLabelE1 = new javax.swing.JLabel();
        jLabelN1 = new javax.swing.JLabel();
        jLabelI1 = new javax.swing.JLabel();
        jLabelD = new javax.swing.JLabel();
        jLabelO = new javax.swing.JLabel();
        jLabelImagen = new javax.swing.JLabel();
        jPanelBarra = new javax.swing.JPanel();
        jPanelBtn = new javax.swing.JPanel();
        jLabelBotonCerrar = new javax.swing.JLabel();
        jPanelBtnMin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelPswrd = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jSeparatorPswrd = new javax.swing.JSeparator();
        jSeparatorUser = new javax.swing.JSeparator();
        jPanelBtnIngresar = new javax.swing.JPanel();
        jLabelBtnIngresar = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelUsrInvalido = new javax.swing.JLabel();
        jLabelPswdInvalida = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanelFondo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelB.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelB.setForeground(new java.awt.Color(255, 255, 255));
        jLabelB.setText("B");
        jPanelFondo.add(jLabelB, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        jLabelI.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelI.setForeground(new java.awt.Color(255, 255, 255));
        jLabelI.setText("I");
        jPanelFondo.add(jLabelI, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jLabelE.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelE.setForeground(new java.awt.Color(255, 255, 255));
        jLabelE.setText("E");
        jPanelFondo.add(jLabelE, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        jLabelN.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelN.setForeground(new java.awt.Color(255, 255, 255));
        jLabelN.setText("N");
        jPanelFondo.add(jLabelN, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jLabelV.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelV.setForeground(new java.awt.Color(255, 255, 255));
        jLabelV.setText("V");
        jPanelFondo.add(jLabelV, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jLabelE1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelE1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelE1.setText("E");
        jPanelFondo.add(jLabelE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        jLabelN1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelN1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelN1.setText("N");
        jPanelFondo.add(jLabelN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        jLabelI1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelI1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelI1.setText("I");
        jPanelFondo.add(jLabelI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        jLabelD.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelD.setForeground(new java.awt.Color(255, 255, 255));
        jLabelD.setText("D");
        jPanelFondo.add(jLabelD, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));

        jLabelO.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelO.setForeground(new java.awt.Color(255, 255, 255));
        jLabelO.setText("O");
        jPanelFondo.add(jLabelO, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, -1));
        jPanelFondo.add(jLabelImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 196, 490));

        jPanelBarra.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBarra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelBarraMouseDragged(evt);
            }
        });
        jPanelBarra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelBarraMousePressed(evt);
            }
        });
        jPanelBarra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelBtn.setBackground(new java.awt.Color(255, 255, 255));

        jLabelBotonCerrar.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        jLabelBotonCerrar.setForeground(new java.awt.Color(0, 0, 0));
        jLabelBotonCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBotonCerrar.setText("x");
        jLabelBotonCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelBotonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBotonCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBotonCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBotonCerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelBtnLayout = new javax.swing.GroupLayout(jPanelBtn);
        jPanelBtn.setLayout(jPanelBtnLayout);
        jPanelBtnLayout.setHorizontalGroup(
            jPanelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelBotonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelBtnLayout.setVerticalGroup(
            jPanelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelBotonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelBarra.add(jPanelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 30, -1));

        jPanelBtnMin.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("_");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelBtnMinLayout = new javax.swing.GroupLayout(jPanelBtnMin);
        jPanelBtnMin.setLayout(jPanelBtnMinLayout);
        jPanelBtnMinLayout.setHorizontalGroup(
            jPanelBtnMinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBtnMinLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelBtnMinLayout.setVerticalGroup(
            jPanelBtnMinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBtnMinLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelBarra.add(jPanelBtnMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, -1, -1));

        jPanelFondo.add(jPanelBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 30));

        jLabelPswrd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelPswrd.setForeground(new java.awt.Color(0, 0, 0));
        jLabelPswrd.setText("CONTRASEÑA");
        jPanelFondo.add(jLabelPswrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, -1));

        jLabelUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelUser.setForeground(new java.awt.Color(0, 0, 0));
        jLabelUser.setText("USUARIO");
        jPanelFondo.add(jLabelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));
        jPanelFondo.add(jSeparatorPswrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 340, 10));
        jPanelFondo.add(jSeparatorUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 340, 10));

        jPanelBtnIngresar.setBackground(new java.awt.Color(94, 96, 98));

        jLabelBtnIngresar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelBtnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnIngresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBtnIngresar.setText("INGRESAR");
        jLabelBtnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelBtnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBtnIngresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBtnIngresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBtnIngresarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelBtnIngresarLayout = new javax.swing.GroupLayout(jPanelBtnIngresar);
        jPanelBtnIngresar.setLayout(jPanelBtnIngresarLayout);
        jPanelBtnIngresarLayout.setHorizontalGroup(
            jPanelBtnIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBtnIngresarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelBtnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelBtnIngresarLayout.setVerticalGroup(
            jPanelBtnIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBtnIngresarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelBtnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelFondo.add(jPanelBtnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 150, 40));

        jTextFieldUser.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldUser.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldUser.setText("Ingrese su usuario");
        jTextFieldUser.setBorder(null);
        jTextFieldUser.setFocusable(false);
        jTextFieldUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldUserMousePressed(evt);
            }
        });
        jPanelFondo.add(jTextFieldUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 340, 30));

        jPasswordField.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPasswordField.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField.setText("**********");
        jPasswordField.setBorder(null);
        jPasswordField.setFocusable(false);
        jPasswordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPasswordFieldMousePressed(evt);
            }
        });
        jPanelFondo.add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 340, 30));

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitulo.setText("ELECTRONIC-HOMES");
        jPanelFondo.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 360, 140));

        jLabelUsrInvalido.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabelUsrInvalido.setForeground(new java.awt.Color(255, 0, 0));
        jPanelFondo.add(jLabelUsrInvalido, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 170, 20));

        jLabelPswdInvalida.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabelPswdInvalida.setForeground(new java.awt.Color(255, 0, 0));
        jPanelFondo.add(jLabelPswdInvalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 170, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Cambiamos el fondo y el color de fuente en el boton que cierra el programa al posicionar el mouse encima
    private void jLabelBotonCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotonCerrarMouseEntered
        this.jPanelBtn.setBackground(Color.red); //Se cambio el fondo a rojo
        this.jLabelBotonCerrar.setForeground(Color.white); //Se cambia el color de letra a blanco
    }//GEN-LAST:event_jLabelBotonCerrarMouseEntered

    //Cambiamos el fondo y el color de fuente en el boton a la hora de quitar el mouse del mismo
    private void jLabelBotonCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotonCerrarMouseExited
        this.jPanelBtn.setBackground(Color.white); //Regresamos en fondo a blanco
        this.jLabelBotonCerrar.setForeground(Color.black); //Regresamos la fuente a negro
    }//GEN-LAST:event_jLabelBotonCerrarMouseExited

    //Metodo que cierra el programa al clickear el boton
    private void jLabelBotonCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotonCerrarMouseClicked
        System.exit(0); //Cerramos el programa
    }//GEN-LAST:event_jLabelBotonCerrarMouseClicked

    //Metodo que obtiene las cordenadas del mouse a la hora de presionar la barra
    private void jPanelBarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBarraMousePressed
        this.mouseX = evt.getX(); //Obtiene la posicion en el eje X
        this.mouseY = evt.getY(); //Obtiene la posicoin en el eje Y
    }//GEN-LAST:event_jPanelBarraMousePressed

    //Metodo que se encarga de arrastrar la ventana a donde queramos
    private void jPanelBarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBarraMouseDragged
        int posicionX = evt.getXOnScreen(); //Posicion final de la ventana
        int posicionY = evt.getYOnScreen(); //Posicion final de la ventana
        this.setLocation(posicionX - this.mouseX, posicionY - this.mouseY); //Posicion final de la ventana
    }//GEN-LAST:event_jPanelBarraMouseDragged

    private void jLabelBtnIngresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnIngresarMouseEntered
        this.jPanelBtnIngresar.setBackground(new Color(152, 155, 158)); //Cambia el color en el boton ingresar al pasar el raton
    }//GEN-LAST:event_jLabelBtnIngresarMouseEntered

    private void jLabelBtnIngresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnIngresarMouseExited
        this.jPanelBtnIngresar.setBackground(new Color(94, 96, 98)); //Regresa el color por defecto al boton al salir el raton
    }//GEN-LAST:event_jLabelBtnIngresarMouseExited

    private void jTextFieldUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldUserMousePressed
        if (this.jTextFieldUser.getText().equals("Ingrese su usuario")) { //Valida que es el texto por defecto
            this.jTextFieldUser.setText(""); //Setea el texto
            this.jTextFieldUser.setForeground(Color.black); //Cambio el color de fuente
            this.jTextFieldUser.setFocusable(true); //Habilita la Escritura
            this.jTextFieldUser.requestFocus();
        }
        if (String.valueOf(this.jPasswordField.getPassword()).isEmpty()) { //Valida si no hay contraseña
            this.jPasswordField.setForeground(new Color(153, 153, 153)); //Cambia el color de la fuetne de la contrasenia
            this.jPasswordField.setText("**********"); //Setea el texto de la contrasenia
            this.jPasswordField.setFocusable(false); //Deshabilita la escritura
            this.jPasswordField.requestFocus();
        }
    }//GEN-LAST:event_jTextFieldUserMousePressed

    private void jPasswordFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordFieldMousePressed
        // TODO add your handling code here:
        if (String.valueOf(this.jPasswordField.getPassword()).equals("**********")) { //valida si es la contrasenia por defecto 
            this.jPasswordField.setText(""); //Sete la contrasenia
            this.jPasswordField.setForeground(Color.black); //Cambia el color de fuente a negro
            this.jPasswordField.setFocusable(true); //Habilita la escritura
            this.jPasswordField.requestFocus();
        } 
        if (this.jTextFieldUser.getText().isEmpty()) { //Valida si no hay usuario
            this.jTextFieldUser.setForeground(new Color(153, 153, 153)); //Cambio el color de fuente de usuario
            this.jTextFieldUser.setText("Ingrese su usuario"); //Setea al texto por defecto
            this.jTextFieldUser.setFocusable(false); //Deshabilita la escritura
            this.jTextFieldUser.requestFocus();
        }
    }//GEN-LAST:event_jPasswordFieldMousePressed

    private void jLabelBtnIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnIngresarMouseClicked
       Vendedor ui = new Vendedor(); 
       this.setVisible(false);
    }//GEN-LAST:event_jLabelBtnIngresarMouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        this.jPanelBtnMin.setBackground(new Color(235, 235, 235)); //Oscurece el boton minimizar
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        this.jPanelBtnMin.setBackground(Color.white); //Regresa el color originar del boton
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.setExtendedState(Login.ICONIFIED); //Minimiza la ventana
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelB;
    private javax.swing.JLabel jLabelBotonCerrar;
    private javax.swing.JLabel jLabelBtnIngresar;
    private javax.swing.JLabel jLabelD;
    private javax.swing.JLabel jLabelE;
    private javax.swing.JLabel jLabelE1;
    private javax.swing.JLabel jLabelI;
    private javax.swing.JLabel jLabelI1;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JLabel jLabelN;
    private javax.swing.JLabel jLabelN1;
    private javax.swing.JLabel jLabelO;
    private javax.swing.JLabel jLabelPswdInvalida;
    private javax.swing.JLabel jLabelPswrd;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JLabel jLabelUsrInvalido;
    private javax.swing.JLabel jLabelV;
    private javax.swing.JPanel jPanelBarra;
    private javax.swing.JPanel jPanelBtn;
    private javax.swing.JPanel jPanelBtnIngresar;
    private javax.swing.JPanel jPanelBtnMin;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JSeparator jSeparatorPswrd;
    private javax.swing.JSeparator jSeparatorUser;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
}
