/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tiendasql.UI;

import java.awt.Color;
import java.awt.Toolkit;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;


/**
 *
 * @author lroda
 */
public class Vendedor_Pnl1 extends javax.swing.JPanel {

    /**
     * Creates new form VendedorP1
     */
    public Vendedor_Pnl1() {
        initComponents();      
        Date date = new Date();
        DateFormat dateformat = new SimpleDateFormat("yyyy/MM/dd");
        this.jLabelFecha.setText(dateformat.format(date));
        this.jLabelSucursal.setText("Sucursal Central");
        this.jPanelCompra.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTituloFecha = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jLabelSucursal = new javax.swing.JLabel();
        jLabelNIT = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelGenerar = new javax.swing.JPanel();
        jLabelGenerar = new javax.swing.JLabel();
        jTextFieldNIT = new javax.swing.JTextField();
        jPanelCompra = new javax.swing.JPanel();
        jLabelProducto = new javax.swing.JLabel();
        jTextFieldCodProd = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSpinnerCantidad = new javax.swing.JSpinner();
        jLabelCantidad = new javax.swing.JLabel();
        jPanelBuscar = new javax.swing.JPanel();
        jLabelBuscar = new javax.swing.JLabel();
        jPanelAgregar = new javax.swing.JPanel();
        jLabelAgregar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTituloFecha.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelTituloFecha.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTituloFecha.setText("Fecha: ");
        add(jLabelTituloFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 90, -1));

        jLabelFecha.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelFecha.setForeground(new java.awt.Color(0, 0, 0));
        jLabelFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(jLabelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 160, 30));

        jLabelSucursal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelSucursal.setForeground(new java.awt.Color(0, 0, 0));
        jLabelSucursal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        add(jLabelSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, 200, 30));

        jLabelNIT.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelNIT.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNIT.setText("NIT:");
        add(jLabelNIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 120, 10));

        jPanelGenerar.setBackground(new java.awt.Color(94, 96, 98));
        jPanelGenerar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelGenerar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelGenerarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelGenerarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelGenerarMouseExited(evt);
            }
        });

        jLabelGenerar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelGenerar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGenerar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGenerar.setText("GENERAR");

        javax.swing.GroupLayout jPanelGenerarLayout = new javax.swing.GroupLayout(jPanelGenerar);
        jPanelGenerar.setLayout(jPanelGenerarLayout);
        jPanelGenerarLayout.setHorizontalGroup(
            jPanelGenerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGenerarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelGenerarLayout.setVerticalGroup(
            jPanelGenerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGenerarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanelGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 130, 30));

        jTextFieldNIT.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNIT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldNIT.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldNIT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNIT.setBorder(null);
        jTextFieldNIT.setFocusable(false);
        jTextFieldNIT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldNITMousePressed(evt);
            }
        });
        jTextFieldNIT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNITKeyTyped(evt);
            }
        });
        add(jTextFieldNIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 120, 30));

        jPanelCompra.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCompra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelProducto.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelProducto.setForeground(new java.awt.Color(0, 0, 0));
        jLabelProducto.setText("Codigo Producto:");
        jPanelCompra.add(jLabelProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTextFieldCodProd.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCodProd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldCodProd.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldCodProd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCodProd.setBorder(null);
        jTextFieldCodProd.setFocusable(false);
        jTextFieldCodProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldCodProdMousePressed(evt);
            }
        });
        jTextFieldCodProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCodProdKeyTyped(evt);
            }
        });
        jPanelCompra.add(jTextFieldCodProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 140, 30));
        jPanelCompra.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 32, 140, 10));

        jSpinnerCantidad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jSpinnerCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jSpinnerCantidad.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jSpinnerCantidad.setEnabled(false);
        jPanelCompra.add(jSpinnerCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 50, 30));

        jLabelCantidad.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelCantidad.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCantidad.setText("Cantidad:");
        jPanelCompra.add(jLabelCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, -1, -1));

        jPanelBuscar.setBackground(new java.awt.Color(94, 96, 98));

        jLabelBuscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBuscar.setText("BUSCAR");
        jLabelBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBuscarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelBuscarLayout = new javax.swing.GroupLayout(jPanelBuscar);
        jPanelBuscar.setLayout(jPanelBuscarLayout);
        jPanelBuscarLayout.setHorizontalGroup(
            jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
        );
        jPanelBuscarLayout.setVerticalGroup(
            jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanelCompra.add(jPanelBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, -1, 30));

        jPanelAgregar.setBackground(new java.awt.Color(94, 96, 98));
        jPanelAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelAgregar.setEnabled(false);
        jPanelAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelAgregarMouseExited(evt);
            }
        });

        jLabelAgregar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelAgregar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAgregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAgregar.setText("AGREGAR");

        javax.swing.GroupLayout jPanelAgregarLayout = new javax.swing.GroupLayout(jPanelAgregar);
        jPanelAgregar.setLayout(jPanelAgregarLayout);
        jPanelAgregarLayout.setHorizontalGroup(
            jPanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAgregarLayout.createSequentialGroup()
                .addComponent(jLabelAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jPanelAgregarLayout.setVerticalGroup(
            jPanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanelCompra.add(jPanelAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 100, 30));

        add(jPanelCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 800, 440));

        getAccessibleContext().setAccessibleParent(this);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelGenerarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelGenerarMouseEntered
        // TODO add your handling code here:
        if (this.jPanelGenerar.isEnabled()) {
            this.jPanelGenerar.setBackground(new Color (152, 155, 158));
        }
    }//GEN-LAST:event_jPanelGenerarMouseEntered

    private void jPanelGenerarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelGenerarMouseExited
        // TODO add your handling code here:
        this.jPanelGenerar.setBackground(new Color (94, 96, 98));
    }//GEN-LAST:event_jPanelGenerarMouseExited

    private void jPanelGenerarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelGenerarMouseClicked
        // TODO add your handling code here:
        this.jTextFieldNIT.setFocusable(false);
        this.jTextFieldNIT.requestFocus();
        this.jTextFieldNIT.setEditable(false);   
        if (this.jTextFieldNIT.getText().isEmpty()) {
            this.jTextFieldNIT.setText("C/F");
            System.out.println("Es consumidor Final");
        }
        this.jPanelGenerar.setEnabled(false);
        this.jPanelCompra.setVisible(true);
    }//GEN-LAST:event_jPanelGenerarMouseClicked

    private void jTextFieldNITKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNITKeyTyped
        // TODO add your handling code here:
        if (this.jTextFieldNIT.getText().length() > 7) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
        if (!(evt.getKeyChar() >= 48 && evt.getKeyChar() <= 57)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNITKeyTyped

    private void jTextFieldNITMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNITMousePressed
        // TODO add your handling code here:
        this.jTextFieldNIT.setFocusable(true);
        this.jTextFieldNIT.requestFocus();
    }//GEN-LAST:event_jTextFieldNITMousePressed

    private void jTextFieldCodProdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodProdKeyTyped
        // TODO add your handling code here:
        if (this.jTextFieldCodProd.getText().length() > 11) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_jTextFieldCodProdKeyTyped

    private void jTextFieldCodProdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldCodProdMousePressed
        // TODO add your handling code here:
        this.jTextFieldCodProd.setFocusable(true);
        this.jTextFieldCodProd.requestFocus();
    }//GEN-LAST:event_jTextFieldCodProdMousePressed

    private void jLabelBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBuscarMouseEntered
        // TODO add your handling code here:
        if (this.jPanelBuscar.isEnabled()) {
            this.jPanelBuscar.setBackground(new Color(152, 155, 158));
        }
    }//GEN-LAST:event_jLabelBuscarMouseEntered

    private void jLabelBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBuscarMouseExited
        // TODO add your handling code here:
        this.jPanelBuscar.setBackground(new Color(94, 96, 98));
    }//GEN-LAST:event_jLabelBuscarMouseExited

    private void jPanelAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAgregarMouseEntered
        // TODO add your handling code here:
        if (this.jPanelAgregar.isEnabled()) {
            this.jPanelAgregar.setBackground(new Color(152, 155, 158));
        }
    }//GEN-LAST:event_jPanelAgregarMouseEntered

    private void jPanelAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAgregarMouseExited
        // TODO add your handling code here:
        this.jPanelAgregar.setBackground(new Color(94, 96, 98));
    }//GEN-LAST:event_jPanelAgregarMouseExited

    private void jLabelBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBuscarMouseClicked
        // TODO add your handling code here:
        if (!this.jTextFieldCodProd.getText().isEmpty()) {
            this.jPanelAgregar.setEnabled(true);
            this.jSpinnerCantidad.setEnabled(true);
            this.jTextFieldCodProd.setFocusable(false);
            this.jTextFieldCodProd.requestFocus();
            this.jTextFieldCodProd.setEditable(false);
            this.jPanelBuscar.setEnabled(false);
            
        }
    }//GEN-LAST:event_jLabelBuscarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAgregar;
    private javax.swing.JLabel jLabelBuscar;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelGenerar;
    private javax.swing.JLabel jLabelNIT;
    private javax.swing.JLabel jLabelProducto;
    private javax.swing.JLabel jLabelSucursal;
    private javax.swing.JLabel jLabelTituloFecha;
    private javax.swing.JPanel jPanelAgregar;
    private javax.swing.JPanel jPanelBuscar;
    private javax.swing.JPanel jPanelCompra;
    private javax.swing.JPanel jPanelGenerar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner jSpinnerCantidad;
    private javax.swing.JTextField jTextFieldCodProd;
    private javax.swing.JTextField jTextFieldNIT;
    // End of variables declaration//GEN-END:variables

}
